services:
  mysql:
    image: docker-images/opencart-mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=opencart
    restart: always
    volumes:
      - mysql:/var/lib/mysql

  opencart:
    image: docker-images/opencart-opencart:latest
    restart: always
    ports:
      - '8080:80'
    volumes:
      - opencart:/var/www
    depends_on:
      - mysql
volumes:
  mysql:
    driver: local
  opencart:
    driver: local